on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@whiskey-platform"
      - name: Install dependencies
        run: pnpm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: whiskey-receipts

      - name: Deploy to AWS
        run: pnpm run deploy
        env:
          NO_BUN: true
          HOSTED_ZONE_ID: ${{ vars.ROUTE_53_HOSTED_ZONE_ID }}
