on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@whiskey-platform"
      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: whiskey-receipts

      - name: Deploy to AWS
        run: pnpm run deploy
        env:
          NO_BUN: true
          HOSTED_ZONE_ID: ${{ vars.ROUTE_53_HOSTED_ZONE_ID }}
          CERT_ARN: ${{ secrets.API_CERTIFICATE_ARN_PROD }}
